name: Build FileGather_Pro2.3.4 for macOS Intel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos-intel:
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # 如有其他依赖请在此补充 pip install xxx

      - name: Build executable
        run: |
          pyinstaller --onefile "4-查找文件工具√/版本2.3.4/FileGather_Pro2.3.4.py"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileGather_Pro2.3.4-macOS-Intel
          path: dist/FileGather_Pro2.3.4
